leftnav:
- identifier: 3e931feb-273b-f725-38f8-43071334cc64
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 91be65cc-0c4b-b519-a6dc-ab754287d391
  name: Lecture Notes and Readings
  pageRef: /pages/lecture-notes-and-readings
  weight: 20
- identifier: 4c12c571-2709-04e3-b740-58ed6a61eb3c
  name: Projects
  pageRef: /pages/projects
  weight: 30
- identifier: 1a6a7ab3-c028-5202-32a3-ef396e13931b
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 40
